
        </div>
        <!-- .container-fluid -->
      </div>
      <!-- #content -->
    </div>
    <!-- .container-fluid -->
  </div>
  <!-- #page -->
  <script src="<?= get_base_url('assets/js/jquery.js');?>"></script>
  <script src="<?= get_base_url('assets/js/bootstrap.min.js');?>"></script>
  <script src="<?= get_base_url('assets/js/select2-full.min.js');?>"></script>
  <script src="<?= get_base_url('assets/js/bootstrap3-wysihtml5/bootstrap3-wysihtml5.all.min.js');?>"></script>
  <script src="<?= get_base_url('assets/js/app.js');?>"></script>
</body>
</html>